TICKERS = {'USDCHF': "CHF=X", 
    'GBPUSD': "GBPUSD=X", 
    'EURUSD': "EURUSD=X", 
    'USDJPY': "JPY=X", 
    'USDCAD': "CAD=X", 
    'AUDUSD': "AUDUSD=X", 
    'EURGBP': "EURGBP=X", 
    'EURAUD': "EURAUD=X", 
    'EURCHF': "EURCHF=X" ,
    'EURJPY': "EURJPY=X", 
    'GBPCHF': "GBPCHF=X",
    'CADJPY': "CADJPY=X",
    'GBPJPY': "GBPJPY=X",
    'AUDNZD': "AUDNZD=X",
    'AUDCAD': "AUDCAD=X",
    'AUDCHF': "AUDCHF=X",
    'AUDJPY': "AUDJPY=X",
    'CHFJPY': "CHFJPY=X",
    'EURNZD': "EURNZD=X",
    'EURCAD': "EURCAD=X",
    'CADCHF': "CADCHF=X",
    'NZDJPY': "NZDJPY=X",
    'NZDUSD': "NZDUSD=X",
    }